[package]
name = "nodarium_types"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Types for Nodarium"
repository = "https://github.com/jim-fx/nodes"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
