services:
  app:
    image: denoland/deno:latest
    working_dir: /app
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://nodarium:nodarium@db:5432/nodarium
    volumes:
      - .:/app
      - deno-cache:/deno-dir/ 
    command: task dev
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: nodarium
      POSTGRES_PASSWORD: nodarium
      POSTGRES_DB: nodarium
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  deno-cache:
