[package]
name = "nodarium_utils"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/jim-fx/nodes"
description = "A collection of utilities for Nodarium"

[lib]
crate-type = ["rlib"]

[dependencies]
glam = "0.30.10"
noise = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
